import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import StoreProvider from "./StoreProvider";
import "./globals.css";

// Components
import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";
import Loading from "@/app/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Suspense fallback={<Loading />}>
            <Header />
            {children}
          </Suspense>
        </body>
      </html>
    </StoreProvider>

  );
}
